GEM-229 | Asynchronous settlements
Group-Expense-Manager/finance-adapter pull request #9
Opened 2024-10-15 21:14 UTC by lawos98

2024-10-16 07:44 UTC, pwgacek requested changes

2024-10-16 07:44 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpenseTest.kt
please change BalanceElements to BalanceList in test names

2024-10-16 07:44 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpense.kt
i think that we should revert sign (if A pays of B and C 4$ each Balance shouldBe: A:-8$, B:4$, C:4$, but currently it is A:8$, B:-4$, C:-4$) Same in AcceptedPayments

2024-10-16 07:44 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/BaseIntegrationSpec.kt
> +        val FIXED_WEDNESDAY = Instant.parse("2021-01-06T00:00:00Z")
not used

2024-10-16 07:44 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/FinanceService.kt
> +        val expenseBalanceList = expenseManagerClient.getAcceptedExpenses(groupId)
please modify it to use updated versions of expense and payment managers

2024-10-16 07:44 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/persistence/balance/SettlementsEntity.kt
please rename file

2024-10-16 07:44 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/job/ProcessingStage.kt
> +    fun failure(exception: Exception): StageResult {
should it be not used?

2024-10-16 17:46 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/service/FinanceService.kt
> +        return balancesRepository.getBalances(groupId)
check if we have all users and all currenceis in the balances list if not we fetch new

2024-10-16 20:10 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpense.kt
no i think is A pays for that expense its balance should be grater than 0 so if all participants will make settlements, A will be +8 not -8

2024-10-16 20:25 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpense.kt
Settlements are made from positive balances (B :4€, C:4€) to negative (-8€) thats how work all allgorithms. So making it reveresd is not intuitive

2024-10-16 21:22 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpense.kt
Settlements yes, but we talk about balances

2024-10-17 04:51 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/model/expense/AcceptedExpense.kt
ok

2024-10-17 05:02 UTC, pwgacek approved these changes

2024-10-18 22:39 UTC, merged